### ISSUE TITLE
lidar_simulator.F90  Divide by zero?  Bounds on tautot_ice

### ISSUE THREAD

**Issue by gitleviglenn** [CFMIP/COSPv1#2]
This is an issue that has come up when running COSP v1.4.1 in 'debug mode' at gfdl.  The error doesn't come up and the model runs without crashing when run in production mode with fewer checks.  

Concerning the Lidar Simulator, in lidar_simulator.F90, we are finding that in some cases, large values are being used for tautot_ice.  Because this is used as the argument of a negative exponential, and is the denominator of beta_perp_ice it can create a problem.  

Is this a bug?  What upper bound should I expect for tautot_ice values?

**Comment by gitleviglenn** [comment]
Here are the offending lines of code that should have been in the previous comment: 

      DO k= nlev-1, 1, -1
        tautot_lay_ice(:) = tautot_ice(:,k)-tautot_ice(:,k+1)
        WHERE (tautot_lay_ice(:).GT.0.)
         beta_perp_ice(:,k) = pnorm_perp_ice(:,k)/ EXP(-2.0*tautot_ice(:,k+1)) * (2.*tautot_lay_ice(:)) &
            & / (1.-exp(-2.0*tautot_lay_ice(:)))

        ELSEWHERE
         beta_perp_ice(:,k)=pnorm_perp_ice(:,k)/EXP(-2.0*tautot_ice(:,k+1))
        END WHERE
      ENDDO

**Comment by gitleviglenn** [comment]
@byrdman1982

**Comment by alejandrobodas** [comment]
Hi Levi, thanks for reporting this. I think this is a bug, as the exponential is an attenuation term and it should be multiplying, not dividing. This also happens for the liquid part of the perpendicular component. I have asked G. Cesana to confirm if my interpretation is correct.

**Comment by byrdman1982** [comment]
@alejandrobodas we are getting values of about 375 in tautot_ice.  Are these reasonable values?  They are causing the term `EXP(-2.0*tautot_ice(:,k+1))` to become 0.  If these are used for multiplying, then beta_perp_ice will become 0.  

We are seeing the same type of issue with the tautot_liq term as well, just later in the model run.

**Comment by alejandrobodas** [comment]
@byrdman1982 These are pretty big values, but they should not make the algorithm to fail. I think this has uncovered a bug.

**Comment by dustinswales** [comment]
@alejandrobodas 
@gitleviglenn 
After some digging it appears that this is not a bug. In the above lines of code the LIDAR simulator is inverting the equation to compute the lidar backsignal to solve for the backscatter coefficients (Eq 1. from doi:10.1029/2008GL034207). Equations 7 and 8 in the attached note.
Dustin
[note_lidarSim.pdf](https://github.com/CFMIP/COSPv1/files/1808116/note_lidarSim.pdf)

**Comment by alejandrobodas** [comment]
@dustinswales @gitleviglenn 
Dustin, thanks for looking into this. That's good news. Then, we only need to protect for the division by zero, but otherwise the algorithm is fine.

**Comment by gitleviglenn** [comment]
Hi Dustin,

thank you for finishing this up.

Levi
