### ISSUE TITLE
modis simulator divide by zero

### ISSUE THREAD

**Issue by gitleviglenn** [CFMIP/COSPv1#3]
There are several places in the modis_simulator.F90 where a divide by 0 was occurring.

506     ! ########################################################################################
 507     ! Compute mean optical thickness.
 508     ! ########################################################################################
 509     Optical_Thickness_Total_Mean(1:nPoints) = sum(optical_thickness, mask = cloudMask,      dim = 2) / &
 510                                               Cloud_Fraction_Total_Mean(1:nPoints)
 511     Optical_Thickness_Water_Mean(1:nPoints) = sum(optical_thickness, mask = waterCloudMask, dim = 2) / &
 512                                               Cloud_Fraction_Water_Mean(1:nPoints)
 513     Optical_Thickness_Ice_Mean(1:nPoints)   = sum(optical_thickness, mask = iceCloudMask,   dim = 2) / &
 514                                               Cloud_Fraction_Ice_Mean(1:nPoints)
 515 
 516     ! ########################################################################################
 517     ! We take the absolute value of optical thickness here to satisfy compilers that complains 
 518     ! when we evaluate the logarithm of a negative number, even though it's not included in 
 519     ! the sum. 
 520     ! ########################################################################################
 521     Optical_Thickness_Total_MeanLog10(1:nPoints) = sum(log10(abs(optical_thickness)), mask = cloudMask, &
 522          dim = 2) / Cloud_Fraction_Total_Mean(1:nPoints)
 523     Optical_Thickness_Water_MeanLog10(1:nPoints) = sum(log10(abs(optical_thickness)), mask = waterCloudMask,&
 524          dim = 2) / Cloud_Fraction_Water_Mean(1:nPoints)
 525     Optical_Thickness_Ice_MeanLog10(1:nPoints) = sum(log10(abs(optical_thickness)), mask = iceCloudMask,&
 526          dim = 2) / Cloud_Fraction_Ice_Mean(1:nPoints)
 527     Cloud_Particle_Size_Water_Mean(1:nPoints) = sum(particle_size, mask = waterCloudMask, dim = 2) / &
 528          Cloud_Fraction_Water_Mean(1:nPoints)
 529     Cloud_Particle_Size_Ice_Mean(1:nPoints) = sum(particle_size, mask = iceCloudMask,   dim = 2) / &
 530          Cloud_Fraction_Ice_Mean(1:nPoints)
 531     Cloud_Top_Pressure_Total_Mean(1:nPoints) = sum(cloud_top_pressure, mask = cloudMask, dim = 2) / &
 532          max(1, count(cloudMask, dim = 2))
 533     Liquid_Water_Path_Mean(1:nPoints) = LWP_conversion*sum(particle_size*optical_thickness, &
 534          mask=waterCloudMask,dim=2)/Cloud_Fraction_Water_Mean(1:nPoints)
 535     Ice_Water_Path_Mean(1:nPoints) = LWP_conversion * ice_density*sum(particle_size*optical_thickness,&
 536          mask=iceCloudMask,dim = 2) /Cloud_Fraction_Ice_Mean(1:nPoints)

There are many instances where some value in Cloud_Fraction_Total_Mean(1:nPoints) is 0. The NANs are handled later on with some where statements, but calculating NANs is less than desirable.

Is this a known issue?  We have a fix in place, but it would be nice to get some feedback on it.  Thanks in advance.

**Comment by gitleviglenn** [comment]
@byrdman1982

**Comment by gitleviglenn** [comment]
@dustinswales 
@robertpincus

**Comment by dustinswales** [comment]
This issue has been resolved.

**Comment by gitleviglenn** [comment]
As well as this.
